"""Contract-compatible routes."""
from datetime import datetime
from typing import Any, Literal

from fastapi import APIRouter, Body, Depends, HTTPException, Query, status
from pydantic import BaseModel, EmailStr, Field, model_validator
from sqlalchemy.orm import Session

from app.controllers import contract_controllers as controllers
from app.crud import message as message_crud
from app.crud import owner as owner_crud
from app.database import get_db
from app.middleware.auth import require_auth
from app.models import Owner
from app.schemas.schemas import MessageVisibilityEnum, ZoneMessageCreate, ZoneMessageResponse
from app.utils.api_response import success_response
from app.websocket.manager import ws_manager

router = APIRouter(tags=["contract"])


class LoginRequest(BaseModel):
    email: EmailStr
    password: str


class RegisterRequest(BaseModel):
    name: str = Field(min_length=1, description="First and last name from setup wizard")
    email: EmailStr
    password: str = Field(min_length=8)
    accountType: Literal["PRIVATE", "EXCLUSIVE"]
    zoneId: str | None = Field(
        default=None,
        description="Zone ID entered manually, generated by system, or scanned via QR",
    )
    address: str = Field(min_length=1, description="Street/city/province/country")

    model_config = {
        "json_schema_extra": {
            "example": {
                "name": "Avery Stone",
                "email": "avery@example.com",
                "password": "strong-password-123",
                "accountType": "PRIVATE",
                "zoneId": "ZONE-7A29",
                "address": "101 Main St, Denver, CO, USA",
            }
        }
    }


class ZoneUpsertRequest(BaseModel):
    name: str
    type: Literal["polygon", "circle", "grid", "dynamic", "proximity", "object", "geofence", "warn", "alert", "restricted", "custom_1", "custom_2"]
    geometry: dict[str, Any] = Field(default_factory=dict)
    config: dict[str, Any] = Field(default_factory=dict)
    id: str | None = None

    @model_validator(mode="before")
    @classmethod
    def normalize_alias_fields(cls, data: Any) -> Any:
        if not isinstance(data, dict):
            return data

        payload = dict(data)

        if payload.get("type") is None and payload.get("zone_type") is not None:
            payload["type"] = payload["zone_type"]

        if payload.get("id") is None and payload.get("zone_id") is not None:
            payload["id"] = payload["zone_id"]

        if payload.get("geometry") is None and payload.get("geo_fence_polygon") is not None:
            payload["geometry"] = payload["geo_fence_polygon"]

        if "config" not in payload:
            payload["config"] = {}
        if (
            isinstance(payload.get("config"), dict)
            and "h3Cells" not in payload["config"]
            and payload.get("h3_cells") is not None
        ):
            payload["config"]["h3Cells"] = payload["h3_cells"]

        return payload


class MessageCreateRequest(BaseModel):
    zoneId: str = Field(description="Target zone identifier")
    type: Literal["NORMAL", "PANIC", "NS_PANIC", "SENSOR"]
    text: str = Field(description="Message body")
    metadata: dict[str, Any] = Field(default_factory=dict)


class ChatMessageCreateRequest(BaseModel):
    """Chat payload accepted by /messages (no trailing slash)."""

    message: str = Field(..., min_length=1, max_length=16_384)
    visibility: Literal["public", "private"]
    receiver_id: int | None = Field(
        default=None,
        ge=1,
        description="Required when visibility is private; omitted for public",
    )


class MemberLocationRequest(BaseModel):
    latitude: float = Field(ge=-90, le=90)
    longitude: float = Field(ge=-180, le=180)


class PushTokenRequest(BaseModel):
    token: str = Field(min_length=10)
    platform: Literal["FCM", "APNS"] = "FCM"


class OwnerContractResponse(BaseModel):
    id: str
    email: EmailStr
    zone_id: str
    first_name: str
    last_name: str
    account_type: Literal["private", "exclusive"]
    address: str
    phone: str | None = None
    active: bool
    expired: bool
    created_at: datetime
    updated_at: datetime
    api_key: str


class ContractSuccessOwnerMeResponse(BaseModel):
    status: Literal["success"]
    data: OwnerContractResponse
    error: None = None


@router.post(
    "/login",
    summary="Contract login",
    description="Mobile contract login endpoint used by setup/login screens.",
)
async def login(payload: LoginRequest, db: Session = Depends(get_db)):
    data = controllers.login(db, payload.model_dump())
    db.commit()
    return success_response(data)


@router.post(
    "/register",
    status_code=status.HTTP_201_CREATED,
    summary="Contract register",
    description="Mobile contract registration endpoint for administrator/user onboarding.",
)
async def register(payload: RegisterRequest, db: Session = Depends(get_db)):
    data = controllers.register(db, payload.model_dump())
    db.commit()
    return success_response(data)


@router.get("/zones")
async def get_zones(owner: Owner = Depends(require_auth), db: Session = Depends(get_db)):
    return success_response(controllers.list_zones(db, owner))


@router.get("/me", response_model=ContractSuccessOwnerMeResponse)
async def get_me(owner: Owner = Depends(require_auth)):
    data = OwnerContractResponse(
        id=str(owner.id),
        email=owner.email,
        zone_id=owner.zone_id,
        first_name=owner.first_name,
        last_name=owner.last_name,
        account_type=owner.account_type.value,
        address=owner.address,
        phone=owner.phone,
        active=owner.active,
        expired=owner.expired,
        created_at=owner.created_at,
        updated_at=owner.updated_at,
        api_key=owner.api_key,
    )
    return success_response(data.model_dump())


@router.post(
    "/zones",
    status_code=status.HTTP_201_CREATED,
    summary="Create contract zone",
    description="Create main/secondary zones during setup wizard flows.",
)
async def post_zones(
    payload: ZoneUpsertRequest,
    owner: Owner = Depends(require_auth),
    db: Session = Depends(get_db),
):
    data = controllers.create_zone(db, owner, payload.model_dump())
    db.commit()
    return success_response(data)


@router.put("/zones/{zone_id}")
async def put_zone(
    zone_id: str,
    payload: ZoneUpsertRequest,
    owner: Owner = Depends(require_auth),
    db: Session = Depends(get_db),
):
    data = controllers.update_zone(db, owner, zone_id, payload.model_dump())
    db.commit()
    return success_response(data)


@router.delete("/zones/{zone_id}")
async def remove_zone(zone_id: str, owner: Owner = Depends(require_auth), db: Session = Depends(get_db)):
    controllers.delete_zone(db, owner, zone_id)
    db.commit()
    return success_response({"deleted": True, "zoneId": zone_id})


@router.post(
    "/messages",
    status_code=status.HTTP_201_CREATED,
    summary="Create contract message",
    description="Create and broadcast message events to zone subscribers.",
)
async def post_messages(
    payload: dict[str, Any] = Body(...),
    owner: Owner = Depends(require_auth),
    db: Session = Depends(get_db),
):
    # Backward-compatible contract payload.
    if all(key in payload for key in ("zoneId", "type", "text")):
        contract_payload = MessageCreateRequest.model_validate(payload)
        data = controllers.create_message(db, owner, contract_payload.model_dump())
        db.commit()
        await ws_manager.broadcast_message(contract_payload.zoneId, data)
        return success_response(data)

    # Compatibility path for clients sending the chat payload shape.
    chat_payload = ChatMessageCreateRequest.model_validate(payload)
    sender = owner_crud.get_owner(db, owner.id)
    if not sender:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Sender owner not found",
        )

    if chat_payload.visibility == MessageVisibilityEnum.PRIVATE.value and chat_payload.receiver_id is None:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail="receiver_id is required for private messages",
        )

    if chat_payload.visibility == MessageVisibilityEnum.PUBLIC.value and chat_payload.receiver_id is not None:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail="receiver_id must be omitted for public messages",
        )

    if chat_payload.receiver_id is not None:
        receiver = owner_crud.get_owner(db, chat_payload.receiver_id)
        if not receiver:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail="Receiver owner not found",
            )
        if receiver.zone_id != sender.zone_id:
            raise HTTPException(
                status_code=status.HTTP_403_FORBIDDEN,
                detail="Receiver is not in the sender zone",
            )

    db_message = message_crud.create_message(
        db,
        sender_id=sender.id,
        payload=ZoneMessageCreate(
            message=chat_payload.message,
            visibility=chat_payload.visibility,
            receiver_id=chat_payload.receiver_id,
        ),
    )
    db.commit()

    return ZoneMessageResponse(
        id=db_message.id,
        zone_id=sender.zone_id,
        sender_id=db_message.sender_id,
        receiver_id=db_message.receiver_id,
        visibility=db_message.visibility,
        message=db_message.message,
        created_at=db_message.created_at,
    )


@router.get("/messages/new")
async def get_new_messages(since: str = Query(...), db: Session = Depends(get_db), owner: Owner = Depends(require_auth)):
    _ = owner
    return success_response(controllers.get_new_messages(db, since))


@router.get("/members")
async def get_members(owner: Owner = Depends(require_auth), db: Session = Depends(get_db)):
    return success_response(controllers.get_members(db, owner))


@router.post("/members/location")
async def post_member_location(
    payload: MemberLocationRequest,
    owner: Owner = Depends(require_auth),
    db: Session = Depends(get_db),
):
    data = controllers.update_location(db, owner, payload.latitude, payload.longitude)
    db.commit()
    return success_response(data)


@router.post("/devices/push-token")
async def post_push_token(
    payload: PushTokenRequest,
    owner: Owner = Depends(require_auth),
    db: Session = Depends(get_db),
):
    data = controllers.register_push_token(db, owner, payload.token, payload.platform)
    db.commit()
    return success_response(data)
